service:
  name: line-serverless-example

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  line:
    handler: handler.line
    events:
      - http:
          method: post
          path: line
